from . import territory as t
##world map contiene i costruttori delle MAPPE e basta inteso come
##le proprietà intrinseche dei territori

def add_as_neighbors(territory1, territory2):
    territory1.add_neighbor(territory2)
    territory2.add_neighbor(territory1)

def init_world_easy():
    NorthAmerica = t.Territory("North America", "none", 6, 0)
    SouthAmerica = t.Territory("South America", "none", 5, 0)
    Europe = t.Territory("Europe", "none", 6, 0)
    NorthernAfrica = t.Territory("Northern Africa", "none", 4, 0)
    SouthernAfrica = t.Territory("Southern Africa", "none", 5, 0)
    WestAsia = t.Territory("West Asia", "none", 5, 0)
    EastAsia = t.Territory("East Asia", "none", 5, 0)
    Oceania = t.Territory("Oceania", "none", 4, 0)

    add_as_neighbors(NorthAmerica, SouthAmerica)
    add_as_neighbors(NorthAmerica, Europe)
    add_as_neighbors(NorthAmerica, EastAsia)
    add_as_neighbors(EastAsia, WestAsia)
    add_as_neighbors(EastAsia, Oceania)
    add_as_neighbors(Europe, WestAsia)
    add_as_neighbors(Europe, NorthernAfrica)
    add_as_neighbors(NorthernAfrica, WestAsia)
    add_as_neighbors(NorthernAfrica, SouthernAfrica)
    add_as_neighbors(Oceania, SouthernAfrica)
    add_as_neighbors(SouthAmerica, SouthernAfrica)

    territories = [NorthAmerica,SouthAmerica,Europe,NorthernAfrica,SouthernAfrica,WestAsia,EastAsia,Oceania]
    return territories

def init_world_medium():
    Alaska = t.Territory("Alaska", "none", 3, 0)
    Greenland = t.Territory("Greenland", "none", 3, 0)
    NOT = t.Territory("North Ovest Territories", "none", 2, 0)
    Alberta = t.Territory("Alberta", "none", 2, 0)
    Ontario = t.Territory("Ontario", "none", 2, 0)
    Quebec = t.Territory("Quebec", "none", 2, 0)
    USAocc = t.Territory("USA West Coast", "none", 4, 0)
    USAor = t.Territory("USA East Coast", "none", 4, 0)
    AMCentr = t.Territory("Central America", "none", 4, 0)
    Venezuela = t.Territory("Venezuela", "none", 2, 0)
    Brazil = t.Territory("Brazil", "none", 3, 0)
    Peru = t.Territory("Peru", "none", 2, 0)
    Argentina = t.Territory("Argentina", "none", 3, 0)
    WEU = t.Territory("Western Europe", "none", 4, 0)
    CEU = t.Territory("Central Europe", "none", 4, 0)
    SEU = t.Territory("Southern Europe", "none", 3, 0)
    UK = t.Territory("British Islands", "none", 2, 0)
    Scandinavia = t.Territory("Scandinavia", "none", 3, 0)
    Iceland = t.Territory("Iceland", "none", 2, 0)
    EEU = t.Territory("Eastern Europe", "none", 3, 0)
    NAF = t.Territory("Northern Africa", "none", 3, 0)
    Egypt = t.Territory("Egypt", "none", 2, 0)
    Congo = t.Territory("Congo", "none", 2, 0)
    EAFR = t.Territory("East Africa", "none", 2, 0)
    SAF = t.Territory("South Africa", "none", 3, 0)
    Madagascar = t.Territory("Madagascar", "none", 2, 0)
    MEAS = t.Territory("Middle East", "none", 4, 0)
    India = t.Territory("India", "none", 4, 0)
    SEA = t.Territory("South East Asia", "none", 3, 0)
    China = t.Territory("China", "none", 4, 0)
    Japan = t.Territory("Japan", "none", 3, 0)
    Mongolia = t.Territory("Mongolia", "none", 2, 0)
    Urals = t.Territory("Urals", "none", 2, 0)
    Afghanistan = t.Territory("Afghanistan", "none", 3, 0)
    Siberia = t.Territory("Siberia", "none", 2, 0)
    Jacuzia = t.Territory("Jacuzia", "none", 2, 0)
    Cita = t.Territory("Cita", "none", 2, 0)
    Kamchatka = t.Territory("Kamchatka", "none", 3, 0)
    Indonesia = t.Territory("Indonesia", "none", 2, 0)
    NewGuinea = t.Territory("New Guinea", "none", 2, 0)
    Australia = t.Territory("Australia", "none", 3, 0)
    NewZ = t.Territory("New Zealand", "none", 3, 0)
    #borders within northern america
    add_as_neighbors(Alaska, NOT)
    add_as_neighbors(Alaska, Alberta)
    add_as_neighbors(Alberta, NOT)
    add_as_neighbors(Alberta, Ontario)
    add_as_neighbors(Alberta, USAocc)
    add_as_neighbors(NOT, Ontario)
    add_as_neighbors(Ontario, Greenland)
    add_as_neighbors(Quebec, Greenland)
    add_as_neighbors(NOT, Greenland)
    add_as_neighbors(Ontario, Quebec)
    add_as_neighbors(Ontario, USAor)
    add_as_neighbors(USAor, USAocc)
    add_as_neighbors(USAor, AMCentr)
    add_as_neighbors(USAocc, AMCentr)
    #borders within southern america
    add_as_neighbors(Venezuela,Brazil)
    add_as_neighbors(Venezuela,Peru)
    add_as_neighbors(Peru,Argentina)
    add_as_neighbors(Peru,Brazil)
    add_as_neighbors(Brazil,Argentina)
    #borders within europe
    add_as_neighbors(Iceland,UK)
    add_as_neighbors(Iceland,Scandinavia)
    add_as_neighbors(UK,Scandinavia)
    add_as_neighbors(UK, CEU)
    add_as_neighbors(UK, WEU)
    add_as_neighbors(Scandinavia, CEU)
    add_as_neighbors(Scandinavia, EEU)
    add_as_neighbors(EEU, CEU)
    add_as_neighbors(EEU, SEU)
    add_as_neighbors(WEU, CEU)
    add_as_neighbors(WEU, SEU)
    add_as_neighbors(SEU, CEU)
    #boerders within africa
    add_as_neighbors(NAF, Egypt)
    add_as_neighbors(NAF, Congo)
    add_as_neighbors(NAF, EAFR)
    add_as_neighbors(EAFR, Congo)
    add_as_neighbors(EAFR, Egypt)
    add_as_neighbors(Congo, SAF)
    add_as_neighbors(EAFR, SAF)
    add_as_neighbors(Madagascar, SAF)
    add_as_neighbors(EAFR, Madagascar)
    #borders within asia
    add_as_neighbors(Afghanistan,Urals)
    add_as_neighbors(Afghanistan,China)
    add_as_neighbors(Afghanistan, MEAS)
    add_as_neighbors(China, MEAS)
    add_as_neighbors(India, MEAS)
    add_as_neighbors(India, China)
    add_as_neighbors(India, SEA)
    add_as_neighbors(China, SEA)
    add_as_neighbors(China, Urals)
    add_as_neighbors(China, Siberia)
    add_as_neighbors(Siberia, Urals)
    add_as_neighbors(China, Mongolia)
    add_as_neighbors(Cita, Mongolia)
    add_as_neighbors(Kamchatka, Mongolia)
    add_as_neighbors(Kamchatka, Jacuzia)
    add_as_neighbors(Kamchatka, Cita)
    add_as_neighbors(Cita, Jacuzia)
    add_as_neighbors(Siberia, Mongolia)
    add_as_neighbors(Siberia, Cita)
    add_as_neighbors(Siberia, Jacuzia)
    add_as_neighbors(Japan, Mongolia)
    add_as_neighbors(Japan, Kamchatka)
    #borders within oceania
    add_as_neighbors(Indonesia, NewGuinea)
    add_as_neighbors(Indonesia, Australia)
    add_as_neighbors(Australia, NewGuinea)
    add_as_neighbors(Australia, NewZ)
    #borders between continents
    #america asia
    add_as_neighbors(Alaska, Kamchatka)
    #namerica samerica
    add_as_neighbors(AMCentr, Venezuela)
    #samerica africa
    add_as_neighbors(NAF, Brazil)
    #africa euripe
    add_as_neighbors(NAF, WEU)
    add_as_neighbors(NAF, SEU)
    add_as_neighbors(Egypt, SEU)
    #oceania asia
    add_as_neighbors(Indonesia, SEA)
    #asia africa
    add_as_neighbors(MEAS, Egypt)
    #asia europe
    add_as_neighbors(MEAS, SEU)
    add_as_neighbors(MEAS, EEU)
    add_as_neighbors(Afghanistan, EEU)
    add_as_neighbors(Urals, EEU)

    territories = [Alaska, Greenland, NOT, Alberta, Ontario, Quebec, USAocc,
                   USAor, AMCentr, Venezuela, Brazil, Peru, Argentina, WEU,
                   CEU, SEU, UK, Scandinavia, Iceland, EEU, NAF, Egypt, Congo,
                   EAFR, SAF, Madagascar, MEAS, India, SEA, China, Japan, Mongolia,
                   Urals, Afghanistan, Siberia, Jacuzia, Cita, Kamchatka, Indonesia, NewGuinea, Australia, NewZ]
    return territories

def init_world_hard():

    URSS = t.Territory("URSS", "none", 3, 0)
    USA = t.Territory("United States", "none", 5, 0)

    # centronord america
    Canada = t.Territory("Canada", "none", 4, 0)
    Mexico = t.Territory("Mexico", "none", 2, 0)
    Cuba = t.Territory("Cuba", "none", 3, 0)
    Guatemala = t.Territory("Guatemala", "none", 1, 0)
    ElSalvador = t.Territory("El Salvador", "none", 1, 0)
    Honduras = t.Territory("Honduras", "none", 2, 0)
    Nicaragua = t.Territory("Nicaragua", "none", 1, 0)
    Haiti = t.Territory("Haiti", "none", 1, 0)
    DRepublic = t.Territory("Dominican Republic", "none", 1, 0)
    CostaRica = t.Territory("Costa Rica", "none", 3, 0)
    Panama = t.Territory("Panama", "none", 2, 0)
    #vicini in centronord america
    add_as_neighbors(USA, Canada)
    add_as_neighbors(USA, Mexico)
    add_as_neighbors(USA, Cuba)
    add_as_neighbors(Mexico, Guatemala)
    add_as_neighbors(Guatemala, ElSalvador)
    add_as_neighbors(Honduras, ElSalvador)
    add_as_neighbors(Guatemala, Honduras)
    add_as_neighbors(Honduras, Nicaragua)
    add_as_neighbors(Honduras, CostaRica)
    add_as_neighbors(Nicaragua, Cuba)
    add_as_neighbors(Nicaragua, CostaRica)
    add_as_neighbors(Cuba, Haiti)
    add_as_neighbors(Haiti, DRepublic)
    add_as_neighbors(Panama, CostaRica)

    #sudamerica
    Venezuela = t.Territory("Venezuela", "none", 2, 0)
    Colombia = t.Territory("Colombia", "none", 1, 0)
    Ecuador = t.Territory("Ecuador", "none", 2, 0)
    Peru = t.Territory("Peru", "none", 2, 0)
    Bolivia = t.Territory("Bolivia", "none", 2, 0)
    Brazil = t.Territory("Brazil", "none", 2, 0)
    Chile = t.Territory("Chile", "none", 3, 0)
    Paraguay = t.Territory("Paraguay", "none", 2, 0)
    Uruguay = t.Territory("Uruguay", "none", 2, 0)
    Argentina = t.Territory("Argentina", "none", 2, 0)
    #vicini in sudamerica
    add_as_neighbors(Venezuela, Colombia)
    add_as_neighbors(Venezuela, Brazil)
    add_as_neighbors(Colombia, Ecuador)
    add_as_neighbors(Ecuador, Peru)
    add_as_neighbors(Peru, Chile)
    add_as_neighbors(Peru, Bolivia)
    add_as_neighbors(Bolivia, Paraguay)
    add_as_neighbors(Chile, Argentina)
    add_as_neighbors(Argentina, Uruguay)
    add_as_neighbors(Argentina, Paraguay)
    add_as_neighbors(Paraguay, Uruguay)
    add_as_neighbors(Uruguay, Brazil)

    # africa
    Morocco = t.Territory("Morocco", "none", 3, 0)
    Algeria = t.Territory("Algeria", "none", 2, 0)
    Tunisia = t.Territory("Tunisia", "none", 2, 0)
    WestAfricanStates = t.Territory("West African States", "none", 2, 0)
    SaharanStates = t.Territory("Saharan States", "none", 1, 0)
    IvoryCoast = t.Territory("Ivory Coast", "none", 2, 0)
    Nigeria = t.Territory("Nigeria", "none", 1, 0)
    Cameroon = t.Territory("Cameroon", "none", 1, 0)
    Congo = t.Territory("Congo", "none", 1, 0)
    Angola = t.Territory("Angola", "none", 1, 0)
    Zimbabwe = t.Territory("Zimbabwe", "none", 1, 0)
    Botswana = t.Territory("Botswana", "none", 2, 0)
    SouthAfrica = t.Territory("South Africa", "none", 3, 0)
    Tanzania = t.Territory("Tanzania", "none", 2, 0)
    Kenya = t.Territory("Kenya", "none", 2, 0)
    Somalia = t.Territory("Somalia", "none", 2, 0)
    Ethiopia = t.Territory("Ethiopia", "none", 1, 0)
    Sudan = t.Territory("Sudan", "none", 1, 0)
    #vicini africa
    add_as_neighbors(Algeria, Tunisia)
    add_as_neighbors(Algeria, Morocco)
    add_as_neighbors(Algeria, SaharanStates)
    add_as_neighbors(Morocco, WestAfricanStates)
    add_as_neighbors(WestAfricanStates, IvoryCoast)
    add_as_neighbors(IvoryCoast, Nigeria)
    add_as_neighbors(SaharanStates, Nigeria)
    add_as_neighbors(Nigeria, Cameroon)
    add_as_neighbors(Cameroon, Congo)
    add_as_neighbors(Congo, Angola)
    add_as_neighbors(Congo, Zimbabwe)
    add_as_neighbors(Angola, Botswana)
    add_as_neighbors(Angola, SouthAfrica)
    add_as_neighbors(Botswana, Zimbabwe)
    add_as_neighbors(Botswana, SouthAfrica)
    add_as_neighbors(Zimbabwe, Tanzania)
    add_as_neighbors(Tanzania, Kenya)
    add_as_neighbors(Kenya, Somalia)
    add_as_neighbors(Somalia, Ethiopia)
    add_as_neighbors(Ethiopia, Sudan)

    # middle east
    Egypt = t.Territory("Egypt", "none", 2, 0)
    Libya = t.Territory("Libya", "none", 2, 0)
    Palestine = t.Territory("occupied Palestine", "none", 4, 0)
    Syria = t.Territory("Syria", "none", 2, 0)
    Iraq = t.Territory("Iraq", "none", 3, 0)
    Iran = t.Territory("Iran", "none", 2, 0)
    GulfStates = t.Territory("Gulf States", "none", 3, 0)
    SaudiArabia = t.Territory("Saudi Arabia", "none", 3, 0)
    Jordan = t.Territory("Jordan", "none", 2, 0)
    Lebanon = t.Territory("Lebanon", "none", 1, 0)
    #middle east neighbors
    add_as_neighbors(Libya, Egypt)
    add_as_neighbors(Egypt, Palestine)
    add_as_neighbors(Palestine, Jordan)
    add_as_neighbors(Palestine, Lebanon)
    add_as_neighbors(Palestine, Syria)
    add_as_neighbors(Lebanon, Jordan)
    add_as_neighbors(Jordan, Iraq)
    add_as_neighbors(Jordan, SaudiArabia)
    add_as_neighbors(GulfStates, SaudiArabia)
    add_as_neighbors(GulfStates, Iraq)
    add_as_neighbors(Iraq, SaudiArabia)
    add_as_neighbors(Iraq, Iran)
    add_as_neighbors(Syria, Lebanon)
    #europe
    SpainPortugal = t.Territory("Spain Portugal", "none", 2, 0)
    France = t.Territory("France", "none", 3, 0)
    Benelux = t.Territory("Benelux", "none", 3, 0)
    UK = t.Territory("UK", "none", 5, 0)
    Norway = t.Territory("Norway", "none", 4, 0)
    Denmark = t.Territory("Denmark", "none", 3, 0)
    Sweden = t.Territory("Sweden", "none", 4, 0)
    Finland = t.Territory("Finland", "none", 4, 0)
    WestGermany = t.Territory("West Germany", "none", 4, 0)
    EastGermany = t.Territory("East Germany", "none", 3, 0)
    Poland = t.Territory("Poland", "none", 3, 0)
    Czechoslovakia = t.Territory("Czechoslovakia", "none", 3, 0)
    Austria = t.Territory("Austria", "none", 4, 0)
    Hungary = t.Territory("Hungary", "none", 3, 0)
    Romania = t.Territory("Romania", "none", 3, 0)
    Bulgaria = t.Territory("Bulgaria", "none", 3, 0)
    Turkey = t.Territory("Turkey", "none", 2, 0)
    Greece = t.Territory("Greece", "none", 2, 0)
    Yugoslavia = t.Territory("Yugoslavia", "none", 3, 0)
    Italy = t.Territory("Italy", "none", 2, 0)

    #vicini europa
    add_as_neighbors(SpainPortugal, France)
    add_as_neighbors(SpainPortugal, Italy)
    add_as_neighbors(France, UK)
    add_as_neighbors(France, WestGermany)
    add_as_neighbors(France, Italy)
    add_as_neighbors(Italy, Austria)
    add_as_neighbors(Italy, Yugoslavia)
    add_as_neighbors(Italy, Greece)
    add_as_neighbors(UK, Norway)
    add_as_neighbors(UK, Benelux)
    add_as_neighbors(WestGermany, Benelux)
    add_as_neighbors(WestGermany, Denmark)
    add_as_neighbors(WestGermany, EastGermany)
    add_as_neighbors(WestGermany, Austria)
    add_as_neighbors(EastGermany, Austria)
    add_as_neighbors(EastGermany, Czechoslovakia)
    add_as_neighbors(EastGermany, Poland)
    add_as_neighbors(Norway, Sweden)
    add_as_neighbors(Sweden, Denmark)
    add_as_neighbors(Sweden, Finland)
    add_as_neighbors(Czechoslovakia, Poland)
    add_as_neighbors(Czechoslovakia, Hungary)
    add_as_neighbors(Hungary, Austria)
    add_as_neighbors(Hungary, Yugoslavia)
    add_as_neighbors(Hungary, Romania)
    add_as_neighbors(Romania, Yugoslavia)
    add_as_neighbors(Romania, Turkey)
    add_as_neighbors(Bulgaria, Turkey)
    add_as_neighbors(Bulgaria, Greece)
    add_as_neighbors(Greece, Turkey)
    add_as_neighbors(Greece, Yugoslavia)
    add_as_neighbors(URSS, Finland)
    add_as_neighbors(URSS, Poland)
    add_as_neighbors(URSS, Romania)

    #asia and oceania
    Afghanistan = t.Territory("Afghanistan", "none", 2, 0)
    Pakistan = t.Territory("Pakistan", "none", 2, 0)
    India = t.Territory("India", "none", 3, 0)
    Burma = t.Territory("Burma", "none", 2, 0)
    Laos = t.Territory("Laos", "none", 1, 0)
    Thailand = t.Territory("Thailand", "none", 2, 0)
    Vietnam = t.Territory("Vietnam", "none", 1, 0)
    Malaysia = t.Territory("Malaysia", "none", 2, 0)
    Indonesia = t.Territory("Indonesia", "none", 1, 0)
    Philippines = t.Territory("Philippines", "none", 2, 0)
    Taiwan = t.Territory("Taiwan", "none", 3, 0)
    China = t.Territory("China", "none", 4, 0)
    NorthKorea = t.Territory("NorthKorea", "none", 3, 0)
    SouthKorea = t.Territory("SouthKorea", "none", 3, 0)
    Japan = t.Territory("Japan", "none", 4, 0)
    Australia = t.Territory("Australia", "none", 4, 0)
    #vicini asiaoceania
    add_as_neighbors(Afghanistan, Pakistan)
    add_as_neighbors(Pakistan, India)
    add_as_neighbors(India, Burma)
    add_as_neighbors(Burma, Laos)
    add_as_neighbors(Laos, Thailand)
    add_as_neighbors(Laos, Vietnam)
    add_as_neighbors(Thailand, Vietnam)
    add_as_neighbors(Thailand, Malaysia)
    add_as_neighbors(Malaysia, Indonesia)
    add_as_neighbors(Malaysia, Australia)
    add_as_neighbors(Indonesia, Philippines)
    add_as_neighbors(Philippines, Japan)
    add_as_neighbors(Japan, Taiwan)
    add_as_neighbors(China, Taiwan)
    add_as_neighbors(NorthKorea, SouthKorea)
    add_as_neighbors(SouthKorea, Japan)
    add_as_neighbors(SouthKorea, Taiwan)

    #vicini intercontinentali
    add_as_neighbors(Panama, Colombia)
    add_as_neighbors(Libya, Tunisia)
    add_as_neighbors(Egypt, Sudan)
    add_as_neighbors(UK, Canada)
    add_as_neighbors(SpainPortugal, Morocco)
    add_as_neighbors(France, Algeria)
    add_as_neighbors(Turkey, Syria)
    add_as_neighbors(USA, Japan)
    add_as_neighbors(URSS, China)
    add_as_neighbors(URSS, NorthKorea)
    add_as_neighbors(URSS, Afghanistan)
    add_as_neighbors(Iran, Afghanistan)
    add_as_neighbors(Iran, Pakistan)

    territories = [URSS, USA, Canada, Mexico, Cuba, Guatemala, ElSalvador, Honduras,
                   Nicaragua, CostaRica, Panama, DRepublic, Haiti,
                   Venezuela, Colombia, Ecuador, Peru, Bolivia, Brazil,
                   Chile, Paraguay, Uruguay, Argentina,
                   Morocco, Algeria, Tunisia, WestAfricanStates, SaharanStates,
                   IvoryCoast, Nigeria, Cameroon, Congo, Angola, Zimbabwe,
                   Botswana, SouthAfrica, Tanzania, Kenya, Somalia, Ethiopia, Sudan,
                   Egypt, Libya, Palestine, Syria, Iraq, Iran, GulfStates,
                   SaudiArabia, Jordan, Lebanon, SpainPortugal, France,
                   Benelux, UK, Norway, Denmark, Sweden, Finland, WestGermany,
                   EastGermany, Poland, Czechoslovakia, Austria, Hungary, Romania,
                   Bulgaria, Turkey, Greece, Yugoslavia, Italy, Afghanistan,
                   Pakistan, India, Burma, Laos, Thailand, Vietnam, Malaysia,
                   Indonesia, Philippines, Taiwan, China, NorthKorea, SouthKorea,
                   Japan, Australia
                   ]

    return territories


def init_world_italian_hunger_games():
    Abruzzo = t.Territory("Abruzzo", "none", 2, 0)
    Basilicata = t.Territory("Basilicata", "none", 1, 0)
    Calabria = t.Territory("Calabria", "none", 3, 0)
    Campania = t.Territory("Campania", "none", 5, 0)
    EmiliaRomagna = t.Territory("Emilia Romagna", "none", 5, 0)
    FVG = t.Territory("Friuli Venezia Giulia", "none", 2, 0)
    Lazio = t.Territory("Lazio", "none", 5, 0)
    Liguria = t.Territory("Liguria", "none", 3, 0)
    Lombardia = t.Territory("Lombardia", "none", 6, 0)
    Marche = t.Territory("Marche", "none", 2, 0)
    Molise = t.Territory("Molise", "none", 1, 0)
    Piemonte = t.Territory("Piemonte", "none", 5, 0)
    Puglia = t.Territory("Puglia", "none", 4, 0)
    Sardegna = t.Territory("Sardegna", "none", 3, 0)
    Sicilia = t.Territory("Sicilia", "none", 5, 0)
    Toscana = t.Territory("Toscana", "none", 4, 0)
    TrentinoAltoAdige = t.Territory("Trentino Alto Adige", "none", 2, 0)
    Umbria = t.Territory("Umbria", "none", 1, 0)
    ValleDAosta = t.Territory("Valle d'Aosta", "none", 1, 0)
    Veneto = t.Territory("Veneto", "none", 5, 0)

    add_as_neighbors(Piemonte, ValleDAosta)
    add_as_neighbors(Piemonte, Liguria)
    add_as_neighbors(Piemonte, Lombardia)
    add_as_neighbors(Lombardia, TrentinoAltoAdige)
    add_as_neighbors(Lombardia, Veneto)
    add_as_neighbors(Lombardia, EmiliaRomagna)
    add_as_neighbors(TrentinoAltoAdige, Veneto)
    add_as_neighbors(Veneto, FVG)
    add_as_neighbors(Veneto, EmiliaRomagna)
    add_as_neighbors(Liguria, EmiliaRomagna)
    add_as_neighbors(Liguria, Toscana)
    add_as_neighbors(EmiliaRomagna, Toscana)
    add_as_neighbors(EmiliaRomagna, Marche)
    add_as_neighbors(Toscana, Marche)
    add_as_neighbors(Toscana, Umbria)
    add_as_neighbors(Toscana, Lazio)
    add_as_neighbors(Umbria, Marche)
    add_as_neighbors(Umbria, Lazio)
    add_as_neighbors(Marche, Lazio)
    add_as_neighbors(Marche, Abruzzo)
    add_as_neighbors(Lazio, Abruzzo)
    add_as_neighbors(Lazio, Molise)
    add_as_neighbors(Lazio, Campania)
    add_as_neighbors(Molise, Campania)
    add_as_neighbors(Molise, Puglia)
    add_as_neighbors(Molise, Abruzzo)
    add_as_neighbors(Puglia, Abruzzo)
    add_as_neighbors(Puglia, Campania)
    add_as_neighbors(Puglia, Basilicata)
    add_as_neighbors(Basilicata, Calabria)
    add_as_neighbors(Basilicata, Campania)
    add_as_neighbors(Sicilia, Calabria)
    add_as_neighbors(Sardegna, Liguria)
    add_as_neighbors(Sardegna, Toscana)
    add_as_neighbors(Sardegna, Campania)

    territories = [Abruzzo, Basilicata, Calabria, Campania,
                   EmiliaRomagna, FVG, Lazio, Liguria,
                   Lombardia, Molise, Piemonte, Puglia,
                   Marche, Sardegna, Sicilia, Toscana,
                   TrentinoAltoAdige, Umbria, ValleDAosta, Veneto]
    return territories